# Generated by Django 2.2.12 on 2022-06-28 13:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=32)),
                ('last_name', models.CharField(max_length=32)),
                ('email', models.EmailField(max_length=32)),
                ('number', models.CharField(max_length=16)),
                ('image', models.FileField(blank=True, null=True, upload_to='images/')),
                ('qualification', models.CharField(choices=[('10th', '10th'), ('12th', '12th'), ('ug', 'ug'), ('pg', 'pg')], default=0, max_length=4)),
                ('message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='StudentMark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('examtype', models.CharField(choices=[('1st-term', '1st-term'), ('Quarterly exam', 'Quarterly exam'), ('2nd-term', '2nd-term'), ('Half-yearly exam', 'Half-yearly exam'), ('3th-term', '3th-term'), ('Annual exam', 'Annual exam')], default=0, max_length=20)),
                ('maths', models.CharField(max_length=32)),
                ('chemistry', models.CharField(max_length=32)),
                ('physics', models.CharField(max_length=32)),
                ('studentid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marks', to='regformapp.Student')),
            ],
        ),
    ]
